stages:
  - build
  - push

variables:
  DOCKERIO_MIRROR: hub.wuhoo.xyz

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.8.1-debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --registry-mirror "${DOCKERIO_MIRROR}"
      --build-arg "CI_PROJECT_PATH"
      --build-arg "CI_PROJECT_PATH"
      --build-arg "CI_PROJECT_URL"
      --build-arg "CI_COMMIT_SHORT_SHA"
      --build-arg "CI_COMMIT_SHA"
      --build-arg "CI_PIPELINE_ID"
      --build-arg "CI_PIPELINE_URL"
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination=image
      --no-push
      --tarPath image.tar
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - image.tar
    when: on_success

push:
  stage: push
  image:
    name: gcr.io/go-containerregistry/crane/debug:v0.9.0
    entrypoint: [""]
  script:
    - crane auth login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - crane push image.tar ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - crane push image.tar ${CI_REGISTRY_IMAGE}:latest
  needs:
    - build

