title: Gerald Wu's Portfolio
resume: "/resume.pdf"
blog: "https://blog.geraldwu.com"

about:
  - title: Software Engineering
    description: |
      I'm primarily a developer focused in Object-Oriented Programming and Backend Systems Development. Both my professional career and schooling has been focused in software development.

      In terms of professional experience, I have worked on very large scale backend systems, both at Google and Amazon.

      I am most familiar with the Java, C, Python, and GoLang languages. I also have some limited experience in C++, C#, JavaScript, and Scala.

      If you want to see some of my more notable projects, please visit the [projects](#projects) section. Or, visit my [self-hosted GitLab](https://gitlab.wuhoo.xyz/jerry) or my [GitHub](https://github.com/geraldwuhoo/) to view all of them.
  - title: IT Operations
    description: |
      I'm a Linux systems administrator, focused on cloud-native deployments and infrastructure as code (IaC).

      All of my [services](https://wuhoo.xyz) are hosted on an on-premise [Kubernetes](https://kubernetes.io/) cluster, deployed entirely via [Terraform](https://www.terraform.io/). Storage is backed by a [Ceph](https://ceph.io/) cluster with dynamic storage provisioning via CSI. All services are deployed via GitOps with [Flux](https://fluxcd.io/). The configuration files for Flux and Terraform can be found at [this repo](https://gitlab.wuhoo.xyz/jerry/homelab-iac).

      This is hosted on-premise on segregated VLANs with limited inter-VLAN routing rules, behind a self-built firewall/router running [OPNsense](https://opnsense.org/) software.

      I am a  
        * [Certified Kubernetes Administrator](https://training.linuxfoundation.org/certification/verify/) (LF-inn96e0qrb)  
        * [Red Hat Certified System Administrator](https://rhtapps.redhat.com/verify/?certId=180-132-714) (180-132-714)

education:
  - school: Brown University
    degree: Sc.B. Computer Science, A.B. Applied Mathematics
    dates: 2017 - 2021

skills:
  - type: Programming
    description: |
      Java, GoLang, C, C++, Python, Rust, SQL
  - type: IT Operations
    description: |
      [Certified Kubernetes Administrator](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/ccb370ed-1fc7-44e9-94be-62ecefbc48b2-gerald-wu-3b7fdc0a-246f-43c7-a2c9-d90809a3dac1-certificate.pdf) (LF-inn96e0qrb)  
      [Red Hat Certified System Administrator](https://rhtapps.redhat.com/verify/?certId=180-132-714) (180-132-714)  
      Kubernetes, GitOps, Terraform, GitLab CI/CD, Docker, VMWare vSphere/vSAN, Ansible, LaTeX, Git

experience:
  - company: Google (YouTube)
    position: Software Engineer
    dates: Jun 2021 - PRESENT
    description: |
      * Worked with **YouTube Commerce Pre-purchase Serving**
          * Serves valid and best offers given the customer's current standing
      * Worked on **migrating backend systems** from existing fragmented infrastructure to a more **unified infrastructure**
          * Ongoing project expected to impact all paying users on the YouTube platform
      * Designed and implemented backend systems features for the new Play payment processor on Android
          * Implemented a system to support payment rollbacks for refunds and payment failures
              * In production serving all Android payment rollbacks
          * Implemented a system to allow for true multiple line item checkout
              * Affected millions of currently existing users
      * Implemented a **backend system** to support the EU's **price transparency initiative**, that requires services to display the lowest price in the past 30 days to users

  - company: Amazon Web Services (AWS)
    position: Software Engineer Intern
    dates: May 2020 - Aug 2020
    description: |
      * Worked with the **Amazon Connect** team &mdash; a **cloud-based** call center as a service product running on **AWS**
      * Built a deployment pipeline for **Safe Dynamic Config (SDC)**
          * Implemented strict templating and config generation to allow for configuration as code
      * Created library from scratch to pull deployed **SDCs** from remote and parse them for **Feature Access Control (FAC)** (Java)
          * Part of an existing effort to migrate **Feature Access Control** from a flat config file in **S3** to a fast, compartmentalized, safe, dynamic config **deployment as code**

  - company: Brown University
    position: Computer Science Teaching Assistant
    dates: Sep 2019 - Dec 2019
    description: |
      * Undergraduate teaching assistant for CSCI 1270: **Database Management Systems**
      * **Intermediate-level** CS course that covers both database design and theoretical database concepts

  - company: Leidos
    position: Software Engineer Intern
    dates: May 2019 - Aug 2019
    description: |
      * Core member of **systems architecture** team for next-gen virtualization approach (VMWare/Red Hat/Kubernetes)
          * Researched, evaluated, proposed, and implemented various architectures involving **VMWare** clustering, VMWare **vSAN**, Red Hat **OpenShift**, and **Kubernetes**
          * Final proposed systems architecture approved for implementation
      * Part of software development team working on **autonomous** (self-driving) sea vessels (C++/Python)
      * Major contributor of **software migration** process from Red Hat 6 to 7 (C++/Python)
          * Significant code rewriting to fit a **microservice** approach

  - company: FMS Inc.
    position: Software Engineer Intern
    dates: May 2018 - Aug 2018
    description: |
      * Cluster analysis in **large-scale graphs** (C#)
      * Implemented secure, PCI-compliant payment integration on the web using Authorize.Net (ASP Classic)

projects:
  - title: Homelab IaC &mdash; a fully HA k8s deployment using Terraform and Flux
    link: "https://gitlab.wuhoo.xyz/jerry/homelab-iac"
    language: Infrastructure as Code
    image: "/images/kubernetes-logo.webp"
    short_description: |
      Starting from minimal working Proxmox and Ceph clusters, this project uses pure Terraform to bootstrap and install a full high availability (HA) deployment of Kubernetes using the k3s distro from Rancher.

      Following k3s bootstrapping, the project uses Flux gitops to deploy all the Kubernetes workloads in the cluster, including automatic secrets encryption/decryption with Mozilla SOPS.

      Both [geraldwu.com](https://geraldwu.com) and [wuhoo.xyz](https://wuhoo.xyz) (and all related services) are hosted on this Kubernetes cluster.

    description: |
      Starting from minimal working Proxmox and Ceph clusters, this project uses pure Terraform to bootstrap and install a full high availability (HA) deployment of Kubernetes using the k3s distro from Rancher. It uses kube-vip to deploy an on-premise cloud load balancer, and uses Ceph as its container storage interface (CSI) for dynamic volume provisioning.
      
      Since the project is implemented in Terraform, it supports idempotent creation/desctruction of the Kubernetes nodes, which allows for easy rolling fixes if necessary. The provisioner also deploys `kured` and Rancher's `system-upgrade-controller` to allow for automatic, rolling updates of both the Kubernetes software and the underyling OS.

      Following k3s bootstrapping, the project uses Flux gitops to deploy all the Kubernetes workloads in the cluster, including automatic secrets encryption/decryption with Mozilla SOPS. This enables self-documenting, auditable configuration of all the workloads as code.
      
      Both [geraldwu.com](https://geraldwu.com) and [wuhoo.xyz](https://wuhoo.xyz) (and all related services) are hosted on this Kubernetes cluster.

  - title: medtracker.io &mdash; An easy, user-friendly med school tracker with Google Docs integration
    link: "https://medtracker.io"
    language: Golang, Next.js, IaC
    image: "/images/medtracker-logo.png"
    description: |
      A webservice to give medical school applicants an easy way to track all their application progress, with a user-friendly dashboard and automatic Google Docs integration. When a user adds a medical school to their profile, a Google Doc is automatically created in their linked Google account associated with the medical school to allow for an easy overview of all applications and their associated statements.

      This project uses Golang on the backend, and Next.js on the frontend. For infrastructure, deployment is fully automated with Terraform to deploy a k3s cluster, Flux to deploy and monitor workloads, and GitLab CI/CD to automatically test, build, and push Docker images.

  - title: Omgur &mdash; A FOSS private front-end for Imgur
    link: "https://gitlab.wuhoo.xyz/jerry/Omgur"
    language: Golang
    image: "/images/imgur-logo.png"
    description: |
      Omgur is a free and open-source private front-end proxy for Imgur, inspired by [Invidious](https://github.com/iv-org/invidious), [Nitter](https://github.com/zedeus/nitter), and [Teddit](https://codeberg.org/teddit/teddit). Omgur runs with no JavaScript, ads, or tracking. All requests are proxied through the Omgur backend to prevent Imgur from tracking IP or JavaScript fingerprint. Easily self-hostable through the Docker image provided by Gitlab CI/CD.

services:
  - title: GitLab CE
    link: "https://git.geraldwu.com"
    logo: "/images/gitlab-logo.png"

  - title: GitLab Container Registry
    link: "https://git.geraldwu.com/gerald/omgur/container_registry"
    logo: "/images/gitlab-logo.png"

  - title: Matrix Synapse
    link: "https://synapse.geraldwu.com"
    logo: "/images/matrix-logo.png"

  - title: Element
    link: "https://element.geraldwu.com"
    logo: "/images/element-logo.png"

  - title: WriteFreely
    link: "https://blog.geraldwu.com"
    logo: "/images/writefreely-logo.png"

  - title: NextCloud
    link: "https://cloud.geraldwu.com"
    logo: "/images/nextcloud-logo.png"

  - title: Collabora Online
    link: "https://collabora.geraldwu.com"
    logo: "/images/collabora-logo.png"

  - title: Seafile
    link: "https://seafile.geraldwu.com"
    logo: "/images/seafile-logo.png"

  - title: EteSync
    link: "https://etesync.geraldwu.com"
    logo: "/images/etesync-logo.png"

  - title: EteSync-Web
    link: "https://pim.geraldwu.com"
    logo: "/images/etesync-logo.png"

  - title: Paperless-ng
    link: "https://paperless.geraldwu.com"
    logo: "/images/paperless-logo.png"

  - title: Gotify
    link: "https://gotify.geraldwu.com"
    logo: "/images/gotify-logo.png"

  - title: PrivateBin
    link: "https://paste.geraldwu.com"
    logo: "/images/privatebin-logo.png"

  - title: Calibre-Web
    link: "https://calibre.geraldwu.com"
    logo: "/images/calibre-logo.png"

  - title: DokuWiki
    link: "https://wiki.geraldwu.com"
    logo: "/images/dokuwiki-logo.png"

  - title: Shynet
    link: "https://shy.geraldwu.com"
    logo: "/images/shynet-logo.png"

contact:
  - type: Email
    username: gw@geraldwu.com
    link: "mailto:gw@geraldwu.com"
  - type: Matrix
    username: "@jerry:wuhoo.xyz"
    link: "https://matrix.to/#/@jerry:wuhoo.xyz"
