title: Gerald Wu's Portfolio
resume: "/resume.pdf"
blog: "https://blog.geraldwu.com"

about:
  - title: Software Engineering
    description: |
      I'm primarily a developer focused in Object-Oriented Programming and Backend Systems Development. Both my professional career and schooling has been focused in software development.

      In terms of professional experience, I have worked on very large scale backend systems, both at Google and Amazon.

      I am most familiar with the Java, C, Python, and GoLang languages. I also have some limited experience in C++, C#, JavaScript, and Scala.

      If you want to see some of my more notable projects, please visit the [projects](#projects) section. Or, visit my [self-hosted GitLab](https://gitlab.wuhoo.xyz/jerry) or my [GitHub](https://github.com/geraldwuhoo/) to view all of them.
  - title: IT Operations
    description: |
      I'm a Linux systems administrator, focused on cloud-native deployments and infrastructure as code (IaC).

      All of my [services](https://wuhoo.xyz) are hosted on an on-premise [Kubernetes](https://kubernetes.io/) cluster, deployed entirely via [Terraform](https://www.terraform.io/). Storage is backed by a [Ceph](https://ceph.io/) cluster with dynamic storage provisioning via CSI. All services are deployed via GitOps with [Flux](https://fluxcd.io/). The configuration files for Flux and Terraform can be found at [this repo](https://gitlab.wuhoo.xyz/jerry/homelab-iac).

      This is hosted on-premise on segregated VLANs with limited inter-VLAN routing rules, behind a self-built firewall/router running [OPNsense](https://opnsense.org/) software.

      I am a  
        * [Certified Kubernetes Administrator](https://training.linuxfoundation.org/certification/verify/) (LF-inn96e0qrb)  
        * [Red Hat Certified System Administrator](https://rhtapps.redhat.com/verify/?certId=180-132-714) (180-132-714)

education:
  - school: Brown University
    degree: Sc.B. Computer Science, A.B. Applied Mathematics
    dates: 2017 - 2021

skills:
  - type: Programming
    description: |
      Java, GoLang, C, C++, Python, Rust, SQL
  - type: IT Operations
    description: |
      [Certified Kubernetes Administrator](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/ccb370ed-1fc7-44e9-94be-62ecefbc48b2-gerald-wu-3b7fdc0a-246f-43c7-a2c9-d90809a3dac1-certificate.pdf) (LF-inn96e0qrb)  
      [Red Hat Certified System Administrator](https://rhtapps.redhat.com/verify/?certId=180-132-714) (180-132-714)  
      Kubernetes, GitOps, Terraform, GitLab CI/CD, Docker, VMWare vSphere/vSAN, Ansible, LaTeX, Git

experience:
  - company: Google
    position: Software Engineer
    dates: Jun 2021 - PRESENT
    description: |
      * YouTube Commerce Pre-purchase Serving

  - company: Amazon Web Services (AWS)
    position: Software Engineer Intern
    dates: May 2020 - Aug 2020
    description: |
      * Worked with the **Amazon Connect** team &mdash; a **cloud-based** call center as a service product running on **AWS**
      * Built a deployment pipeline for **Safe Dynamic Config (SDC)**
          * Implemented strict templating and config generation to allow for configuration as code
      * Created library from scratch to pull deployed **SDCs** from remote and parse them for **Feature Access Control (FAC)** (Java)
          * Part of an existing effort to migrate **Feature Access Control** from a flat config file in **S3** to a fast, compartmentalized, safe, dynamic config **deployment as code**

  - company: Brown University
    position: Computer Science Teaching Assistant
    dates: Sep 2019 - Dec 2019
    description: |
      * Undergraduate teaching assistant for CSCI 1270: **Database Management Systems**
      * **Intermediate-level** CS course that covers both database design and theoretical database concepts

  - company: Leidos
    position: Software Engineer Intern
    dates: May 2019 - Aug 2019
    description: |
      * Part of software development team working on **autonomous** (self-driving) sea vessels (C++/Python)
      * Core member of **systems architecture** team for next-gen virtualization approach (VMWare/Red Hat/Kubernetes)
          * Researched, evaluated, proposed, and implemented various architectures involving **VMWare** clustering, VMWare **vSAN**, Red Hat **OpenShift**, and **Kubernetes**
          * Final proposed systems architecture approved for implementation
      * Major contributor of **software migration** process from Red Hat 6 to 7 (C++/Python)
          * Significant code rewriting to fit a **microservice** approach

  - company: FMS Inc.
    position: Software Engineer Intern
    dates: May 2018 - Aug 2018
    description: |
      * Cluster analysis in **large-scale graphs** (C#)
          * Researched, implemented, and optimized the **Markov Clustering Algorithm** (MCL) to identify clusters in relational graphs of size **100,000+** nodes and **120,000+** edges in less than **10 minutes**
      * Implemented secure, PCI-compliant payment integration on the web using Authorize.Net (ASP Classic)
          * Complete integration with the **Authorize.Net** payment gateway, including both **one-time** payments and long-term customer **payment profiles**

projects:
  - title: Omgur &mdash; A FOSS private front-end for Imgur
    link: "https://git.geraldwu.com/gerald/Omgur"
    language: Golang
    image: "https://geraldwu.com/images/imgur-logo.png"
    description: |
      Omgur is a free and open-source private front-end proxy for Imgur, inspired by [Invidious](https://github.com/iv-org/invidious), [Nitter](https://github.com/zedeus/nitter), and [Teddit](https://codeberg.org/teddit/teddit). Omgur runs with no JavaScript, ads, or tracking. All requests are proxied through the Omgur backend to prevent Imgur from tracking IP or JavaScript fingerprint. Easily self-hostable through the Docker image provided by Gitlab CI/CD configuration.

  - title: Quantum Mechanical Wave Function Propagation
    link: "https://git.geraldwu.com/gerald/QuantumEvolution"
    language: Processing
    image: "https://geraldwu.com/images/quantum.jpg"
    description: |
      A program to evolve arbitrary initial states through time for the one-dimensional Schrodinger Equation and Wave Equation in the absence of a potential field. Highly optimized to run in **real time**. No pre-rendering. Accurate to millions of timesteps before noticeable error propagation. Written in Processing (a fork of Java with a focus on real-time graphing), with a small shell script launcher.

services:
  - title: GitLab CE
    link: "https://git.geraldwu.com"
    logo: "/images/gitlab-logo.png"

  - title: GitLab Container Registry
    link: "https://git.geraldwu.com/gerald/omgur/container_registry"
    logo: "/images/gitlab-logo.png"

  - title: Matrix Synapse
    link: "https://synapse.geraldwu.com"
    logo: "/images/matrix-logo.png"

  - title: Element
    link: "https://element.geraldwu.com"
    logo: "/images/element-logo.png"

  - title: WriteFreely
    link: "https://blog.geraldwu.com"
    logo: "/images/writefreely-logo.png"

  - title: NextCloud
    link: "https://cloud.geraldwu.com"
    logo: "/images/nextcloud-logo.png"

  - title: Collabora Online
    link: "https://collabora.geraldwu.com"
    logo: "/images/collabora-logo.png"

  - title: Seafile
    link: "https://seafile.geraldwu.com"
    logo: "/images/seafile-logo.png"

  - title: EteSync
    link: "https://etesync.geraldwu.com"
    logo: "/images/etesync-logo.png"

  - title: EteSync-Web
    link: "https://pim.geraldwu.com"
    logo: "/images/etesync-logo.png"

  - title: Paperless-ng
    link: "https://paperless.geraldwu.com"
    logo: "/images/paperless-logo.png"

  - title: Gotify
    link: "https://gotify.geraldwu.com"
    logo: "/images/gotify-logo.png"

  - title: PrivateBin
    link: "https://paste.geraldwu.com"
    logo: "/images/privatebin-logo.png"

  - title: Calibre-Web
    link: "https://calibre.geraldwu.com"
    logo: "/images/calibre-logo.png"

  - title: DokuWiki
    link: "https://wiki.geraldwu.com"
    logo: "/images/dokuwiki-logo.png"

  - title: Shynet
    link: "https://shy.geraldwu.com"
    logo: "/images/shynet-logo.png"

contact:
  - type: Email
    username: gw@geraldwu.com
    link: "mailto:gw@geraldwu.com"
  - type: Matrix
    username: "@jerry:wuhoo.xyz"
    link: "https://matrix.to/#/@jerry:wuhoo.xyz"
